function launch_python(remote_ip, remote_port, local_port, bind_port, ...
                       recv_timeout, fps, nb_markers, side, sort_axis)
% LAUNCH_PYTHON  Start the Python bridge in a dedicated xterm terminal.
%
%   launch_python(REMOTE_IP, REMOTE_PORT, LOCAL_PORT, BIND_PORT,
%                 RECV_TIMEOUT, FPS, NB_MARKERS, SIDE, SORT_AXIS)
%
%   All parameters must match the Simulink UDP Send/Receive block settings.
%
%   Arguments:
%     remote_ip    - IP address of the Python host          (string,  e.g. '127.0.0.1')
%     remote_port  - Port Simulink listens on (Python->Simulink) (int, e.g. 25000)
%     local_port   - Port Python listens on  (Simulink->Python)  (int, e.g. 25001)
%     bind_port    - Local port used by Python for sending        (int, e.g. 9090)
%     recv_timeout - Socket timeout waiting for Simulink reply    (float, e.g. 0.1)
%     fps          - Camera framerate [Hz]                        (int, e.g. 30)
%     nb_markers   - Number of markers to track                   (int, e.g. 1)
%     side         - Camera viewpoint: 'top' | 'front' | 'plan'  (string)
%     sort_axis    - Marker sort axis: 'y' | 'z'                  (string)

python_env = './env';
script     = './test.py';
python_bin = fullfile(python_env, 'bin', 'python');

args = sprintf([ ...
    '--remote_ip %s '      ...
    '--remote_port %d '    ...
    '--local_port %d '     ...
    '--bind_port %d '      ...
    '--recv_timeout %.3f ' ...
    '--fps %d '            ...
    '--nb_markers %d '     ...
    '--side %s '           ...
    '--sort %s'            ...
    ], remote_ip, remote_port, local_port, bind_port, ...
       recv_timeout, fps, nb_markers, side, sort_axis);

system(sprintf( ...
    'xterm -title "Bridge Python" -fa "Monospace" -fs 11 -bg black -fg green -e "%s %s %s" &', ...
    python_bin, script, args));

end